/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaregistro.admin;

import Clases.Expediente;
import Clases.GestionExpediente;
import Clases.Nodo;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class ConsultarExpedientes extends javax.swing.JFrame {
    
    private GestionExpediente gestionExp;

    /**
     * Creates new form ConsultarExpedientes
     * @param gestionExp
     */
    public ConsultarExpedientes(GestionExpediente gestionExp) {
        this.gestionExp = gestionExp;
        initComponents();
    }
    
    private void cargarExpedientes(boolean finalizados) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Prioridad");
        modelo.addColumn("DNI");
        modelo.addColumn("Asunto");
        modelo.addColumn("Documento Inicial");
        modelo.addColumn("Documento Resultado");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Final");

        Nodo actual = gestionExp.obtenerExpedientesFiltrados(finalizados);

        while (actual != null) {
            Expediente exp = (Expediente) actual.getElemento();
            modelo.addRow(new Object[]{
                exp.getIdentificador(),
                exp.getPrioridad(),
                exp.getDni(),
                exp.getAsunto(),
                exp.getDocumento(),
                exp.getDocumentoResultado() != null ? exp.getDocumentoResultado() : "N/A",
                exp.getFechaInicio(),
                exp.getFechaFinal() != null ? exp.getFechaFinal() : "Pendiente"
            });
            actual = actual.getSiguiente();
        }

        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtFinalizados = new javax.swing.JButton();
        BtNoFinalizados = new javax.swing.JButton();
        BtCerrarConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtFinalizados.setBackground(new java.awt.Color(255, 149, 50));
        BtFinalizados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtFinalizados.setText("Ver Finalizados");
        BtFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFinalizadosActionPerformed(evt);
            }
        });

        BtNoFinalizados.setBackground(new java.awt.Color(255, 149, 50));
        BtNoFinalizados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtNoFinalizados.setText("Ver No Finalizados");
        BtNoFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNoFinalizadosActionPerformed(evt);
            }
        });

        BtCerrarConsulta.setText("Cerrar");
        BtCerrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCerrarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(BtNoFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(BtFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtCerrarConsulta)
                .addGap(331, 331, 331))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNoFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtCerrarConsulta)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFinalizadosActionPerformed
        // TODO add your handling code here:
        cargarExpedientes(true);
    }//GEN-LAST:event_BtFinalizadosActionPerformed

    private void BtNoFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNoFinalizadosActionPerformed
        // TODO add your handling code here:
        cargarExpedientes(false);
    }//GEN-LAST:event_BtNoFinalizadosActionPerformed

    private void BtCerrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCerrarConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtCerrarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionExpediente gestionExp = new GestionExpediente();
                new ConsultarExpedientes(gestionExp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCerrarConsulta;
    private javax.swing.JButton BtFinalizados;
    private javax.swing.JButton BtNoFinalizados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
