/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaregistro.admin;

import Clases.Expediente;
import Clases.GestionExpediente;
import Clases.Nodo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hidea
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private GestionExpediente gestionExp;
    private Expediente exp;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(GestionExpediente gestionExp) {
        this.gestionExp = gestionExp;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtAgregarExp = new javax.swing.JButton();
        BtListExp = new javax.swing.JButton();
        BtFinTra = new javax.swing.JButton();
        BtSeguimiento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtAgregarExp.setBackground(new java.awt.Color(255, 153, 51));
        BtAgregarExp.setForeground(new java.awt.Color(255, 255, 255));
        BtAgregarExp.setText("Agregar Expediente");
        BtAgregarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarExpActionPerformed(evt);
            }
        });

        BtListExp.setBackground(new java.awt.Color(255, 153, 51));
        BtListExp.setForeground(new java.awt.Color(255, 255, 255));
        BtListExp.setText("Listar Expediente");
        BtListExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtListExpActionPerformed(evt);
            }
        });

        BtFinTra.setBackground(new java.awt.Color(255, 190, 132));
        BtFinTra.setText("Finalizar Trámite");
        BtFinTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFinTraActionPerformed(evt);
            }
        });

        BtSeguimiento.setBackground(new java.awt.Color(255, 153, 51));
        BtSeguimiento.setForeground(new java.awt.Color(255, 255, 255));
        BtSeguimiento.setText("Ver Seguimiento");
        BtSeguimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSeguimientoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("EXPEDIENTES");

        BMovimiento.setBackground(new java.awt.Color(255, 153, 51));
        BMovimiento.setForeground(new java.awt.Color(255, 255, 255));
        BMovimiento.setText("Movimiento");
        BMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtFinTra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(BtSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(BtListExp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSeguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtListExp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(BtFinTra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtAgregarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarExpActionPerformed
        // TODO add your handling code here:
        AgregarExpediente ae = new AgregarExpediente(gestionExp);
        ae.setVisible(true);
    }//GEN-LAST:event_BtAgregarExpActionPerformed

    private void BtListExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtListExpActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo_tabla = new DefaultTableModel();
        this.jTable1.setModel(modelo_tabla);
        modelo_tabla.addColumn("Identificador");
        modelo_tabla.addColumn("Prioridad");
        modelo_tabla.addColumn("Nombre");
        modelo_tabla.addColumn("DNI");
        modelo_tabla.addColumn("Telefono");
        modelo_tabla.addColumn("Correo");
        modelo_tabla.addColumn("Asunto");
        modelo_tabla.addColumn("Documento");
        
        
        Expediente aux;
        Nodo actual =gestionExp.getPrimero();
        int contador = 0;
        if (actual != null) {
            while(actual != null){
                aux = (Expediente) actual.getElemento();
                modelo_tabla.insertRow(contador, new Object[]{
                aux.getIdentificador(),
                aux.getPrioridad(),
                aux.getNombre(),
                aux.getDni(),
                aux.getTelefono(),
                aux.getCorreo(),
                aux.getAsunto(),
                aux.getDocumento()
                
            });
                
                
                contador = contador + 1;
                actual = actual.getSiguiente();
            }
        }
    }//GEN-LAST:event_BtListExpActionPerformed

    private void BtFinTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFinTraActionPerformed
        // TODO add your handling code here:
        FinalizarTramite ft = new FinalizarTramite(this.gestionExp);
        ft.setVisible(true);
    }//GEN-LAST:event_BtFinTraActionPerformed

    private void BtSeguimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSeguimientoActionPerformed
        // TODO add your handling code here:
        ConsultarExpedientes ce = new ConsultarExpedientes(this.gestionExp);
        ce.setVisible(true);
    }//GEN-LAST:event_BtSeguimientoActionPerformed

    private void BMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMovimientoActionPerformed
        // TODO add your handling code here:
        Movimiento rm = new Movimiento();
        rm.setVisible(true);
    }//GEN-LAST:event_BMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        GestionExpediente gestionExp = new GestionExpediente(); // Se crea una sola vez
        new MenuPrincipal(gestionExp).setVisible(true);          // Se pasa al menú principal
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BMovimiento;
    private javax.swing.JButton BtAgregarExp;
    private javax.swing.JButton BtFinTra;
    private javax.swing.JButton BtListExp;
    private javax.swing.JButton BtSeguimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
