/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaregistro.admin;

import Clases.Expediente;
import Clases.GestionExpediente;
import Clases.Nodo;
import Clases.Movimiento;
import Clases.NodoMovimiento;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class VerMovimientos extends javax.swing.JFrame {
    
    private GestionExpediente gestionExp;

    /**
     * Creates new form VerMovimientos
     */
    public VerMovimientos(GestionExpediente gestionExp, String dni) {
        this.gestionExp = gestionExp;
        initComponents();
        cargarMovimientos(dni);
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
    }
    
    private void cargarMovimientos(String dni) {
        System.out.println("Cargando movimientos para DNI: " + dni);
        
        DefaultTableModel modeloMovimientos = new DefaultTableModel();
        modeloMovimientos.addColumn("Movimiento");
        modeloMovimientos.addColumn("Observación");
        modeloMovimientos.addColumn("Fecha");
        
        NodoMovimiento actual = gestionExp.obtenerMovimientoporDNI(dni);
        
        while (actual != null) {
            Movimiento mov = actual.getMovimiento();
            modeloMovimientos.addRow(new Object[]{
                mov.getNombre(),
                mov.getObservacion(),
                mov.getFechaRegistro()
            });
            actual = actual.getSiguiente();
        }
        
        jTableMovimientos.setModel(modeloMovimientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovimientos = new javax.swing.JTable();
        Btregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMovimientos);

        Btregresar.setText("Regresar");
        Btregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(Btregresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Btregresar)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtregresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GestionExpediente gestionExp = new GestionExpediente();

            // Pedir DNI antes de abrir el formulario
            String dni = javax.swing.JOptionPane.showInputDialog(null, "Ingrese el DNI del expediente:");
            if (dni != null && !dni.isEmpty()) {
                new VerMovimientos(gestionExp, dni).setVisible(true);
            }  else {
                javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar un DNI para continuar.");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btregresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMovimientos;
    // End of variables declaration//GEN-END:variables
}
